title: Hack3rlife Website
description: Jekyll Website Hosted on AWS S3 Using GitHub Actions
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

# Deploy a Jekyll site to AWS S3 using GitHub Actions